apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restapi
  name: restapi
spec:
  selector:
    matchLabels:
      app: restapi
  template:
    metadata:
      labels:
        app: restapi
    spec:
      imagePullSecrets:
      - name: pull-secret
      containers:
      - image: imaduddinqurrataayun/restapi:latest
        imagePullPolicy: Always
        name: restapi
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "0.5Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: restapi-svc
spec:
  selector:
    app: restapi
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restapi-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  #ingressClassName: nginx
  rules:
  - host: 'restapi.imad.lyr.id'
    http:
      paths:
      - path: / #/api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: restapi-svc
            port:
              number: 80
  tls:
    - hosts:
      - 'restapi.imad.lyr.id'
      secretName: restapi-tls
